### ISSUE TITLE
Review oneOf and anyOf usage in the spec

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#322]

**Comment by rrutte** [comment]
It would be really helpful from an Azure Devops C# code generation perspective to get rid from anyOf/oneOf. e.g modify expands to seperate attributes/object so the strong typed mechanisms of C# can be used. This example would also eliminate the confusion  of having a person object with only a uuid instead of the complete content (according to the current yamls

In this example for the person properties within schemas/AssociationFul.yaml

````yaml
properties:
   person:
   readOnly: true
   required:
      - personId
   properties:
      personId:
         type: string
         format: uuid
         description: Unique ID of the person
      person:
         $ref: ../schemas/Person.yaml

   
````
